version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - my-database-bertlunch
    environment:
      - ConnectionStrings__BertLunchContextConnection=Server=my-database-bertlunch;port=3306;Database=bertlunch;User Id=root;password=Bertrand49@@@@
    ports:
      - "8080:8080"
      - "443:443"

  my-database-bertlunch:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Bertrand49@@@@
      # MYSQL_DATABASE: bertlunch
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bertlunch_db.sql:/docker-entrypoint-initdb.d/bertlunch_db.sql

volumes:
  mysql_data:
# my-database-bertlunch.internal



