# fly.toml app configuration file generated for bertlunch on 2023-12-30T19:37:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bertlunch"
primary_region = "sin"
kill_timeout = 10
processes = []

[build]
  image = "cwbertrand49/bertlunch:prod"

[env]
  ASPNETCORE_URLS="http://+:8080"
  SecretKey=""
  PublishKey=""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
